### ISSUE TITLE
View misaligned on M3Super90

### ISSUE THREAD

**Issue by brebb** [CiarenceW/M3SUPER90_Plugin#2]
When aiming the Super 90 (loaded and not safe), the front sights are not visible and the gun shoots low because of it. The camera also clips into the stock, and the ammo line at the top of the screen is partway off-screen, so that might be related.

Manual Install:
* M3Super90V1.1.0
* Receiver2ModdingKit v.1.0.1
* BepInEx 5.4.21.0

[Player.log](https://github.com/CiarenceW/M3SUPER90_Plugin/files/11402693/Player.log)
[LogOutput.log](https://github.com/CiarenceW/M3SUPER90_Plugin/files/11402715/LogOutput.log) (BepinEx)
![Receiver2_1683249033_215](https://user-images.githubusercontent.com/49600234/236361417-756d94f5-aa6f-4e38-bd89-8a258fa3406a.png)
![Receiver2_1683249040_384](https://user-images.githubusercontent.com/49600234/236361418-d5606a16-53a5-4387-9d12-315de72cf354.png)
![Receiver2_1683249449_628](https://user-images.githubusercontent.com/49600234/236361648-d303eeb9-76f3-4ddf-9f15-1dfca4a1374e.png)
![Receiver2_1683249527_196](https://user-images.githubusercontent.com/49600234/236361650-28edf37e-4936-4188-9079-2a75fb96407b.png)

**Comment by CiarenceW** [comment]
Hey there! Didn't mean to ghost you for 7 days, I'm an asshole and I don't check my e-mails as often as I should. 
I'm aware of this whole issue. I actually have a "fixed" version that I haven't uploaded yet because I was too busy being lazy as a gator. I'll try to release by the end of the day.

**Comment by brebb** [comment]
No worries king, excited to try the fixed version!

**Comment by CiarenceW** [comment]
Fixed by [new version](https://github.com/CiarenceW/M3SUPER90_Plugin/releases/tag/v1.2.0). Well, except the sights being misaligned, I might suggest lowering the gun distance value a bit, lol.
